### ISSUE TITLE
P1

### ISSUE THREAD

**Issue by JasonSi** [hyacinthee/web_tasks#1]
缩进不正确，你可以从GitHub上看你的代码来验证。

我看到不少缩进不规范的，但python会导致报错呀。直接下载你的文件到本地会报错indent error

**Comment by hyacinthee** [comment]
这可能是我之前条件语句格式不对以及缺少全局变量的声明所导致的 _(:3 」∠)_
然后在缩进方面也稍微调整了一下~

能麻烦学长再看一下吗？谢谢学长~

学长辛苦啦 (=ﾟωﾟ)ﾉ

**Comment by JasonSi** [comment]
很抱歉呀，空格的问题居然是我浏览器插件导致的。误会啦误会啦～
